version: 0.3.1-{build}
pull_requests:
  do_not_increment_build_number: true
environment:
  TWINE_PASSWORD:
    secure: y/ZzELXah34vmsOHWCwMZhrpW0SHo+M6ddPOYZaKzd8=
  TWINE_REPOSITORY: https://pypi.python.org/pypi
  TWINE_REPOSITORY_URL: https://pypi.python.org/pypi
  TWINE_USERNAME: Noctem
  matrix:
  - PYTHON: C:\Python35
  - PYTHON: C:\Python35-x64
  - PYTHON: C:\Python36
  - PYTHON: C:\Python36-x64
install:
- cmd: '%PYTHON%\\python.exe -m pip install -U setuptools wheel cython'
build_script:
- cmd: >-
    %PYTHON%\\python.exe setup.py install

    %PYTHON%\\python.exe setup.py bdist_wheel
test_script:
- cmd: '%PYTHON%\\python.exe test\test_cyrandom.py'
artifacts:
- path: dist\*.whl
  name: Wheel
deploy_script:
- ps: >-
    if($env:appveyor_repo_tag -eq 'True') {
      Invoke-Expression "$env:PYTHON\\python.exe -m pip install -U twine"
      Invoke-Expression "$env:PYTHON\\python.exe -m twine upload dist/*.whl --skip-existing"
    }